### ISSUE TITLE
3.0.1 fails to build on Kinetic buildfarm

### ISSUE THREAD

**Issue by tfoote** [astuff/platform_automation_msgs#16]
It appears to be invalid CMake syntax from a quick look at the error message.

http://build.ros.org/job/Kbin_uX64__automotive_platform_msgs__ubuntu_xenial_amd64__binary/22/console
<details>
15:24:17 if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi && \
15:24:17 dh_auto_configure -- \
15:24:17 	-DCATKIN_BUILD_BINARY_PACKAGE="1" \
15:24:17 	-DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
15:24:17 	-DCMAKE_PREFIX_PATH="/opt/ros/kinetic"
15:24:18 	mkdir -p obj-x86_64-linux-gnu
15:24:18 	cd obj-x86_64-linux-gnu
15:24:18 	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic -DCMAKE_PREFIX_PATH=/opt/ros/kinetic
15:24:18 -- The C compiler identification is GNU 5.4.0
15:24:18 -- The CXX compiler identification is GNU 5.4.0
15:24:18 -- Check for working C compiler: /usr/lib/ccache/x86_64-linux-gnu-gcc
15:24:18 -- Check for working C compiler: /usr/lib/ccache/x86_64-linux-gnu-gcc -- works
15:24:18 -- Detecting C compiler ABI info
15:24:18 -- Detecting C compiler ABI info - done
15:24:18 -- Detecting C compile features
15:24:18 -- Detecting C compile features - done
15:24:18 -- Check for working CXX compiler: /usr/lib/ccache/x86_64-linux-gnu-g++
15:24:18 -- Check for working CXX compiler: /usr/lib/ccache/x86_64-linux-gnu-g++ -- works
15:24:18 -- Detecting CXX compiler ABI info
15:24:19 -- Detecting CXX compiler ABI info - done
15:24:19 -- Detecting CXX compile features
15:24:19 -- Detecting CXX compile features - done
15:24:19 CMake Error at CMakeLists.txt:36 (if):
15:24:19   if given arguments:
15:24:19 
15:24:19     "EQUAL" "1"
15:24:19 
15:24:19   Unknown arguments specified
15:24:19 
15:24:19 
15:24:19 -- Configuring incomplete, errors occurred!
15:24:19 See also "/tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
15:24:19 	cd /tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1
15:24:19 	cd obj-x86_64-linux-gnu
15:24:19 	"tail -v -n +0 CMakeCache.txt"
15:24:19 ==> CMakeCache.txt <==
15:24:19 # This is the CMakeCache file.
15:24:19 # For build in directory: /tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1/obj-x86_64-linux-gnu
15:24:19 # It was generated by CMake: /usr/bin/cmake
15:24:19 # You can edit this file to change values found and used by cmake.
15:24:19 # If you do not want to change any of the values, simply exit the editor.
15:24:19 # If you do want to change a value, simply edit, save, and exit the editor.
15:24:19 # The syntax for the file is as follows:
15:24:19 # KEY:TYPE=VALUE
15:24:19 # KEY is the name of a variable in the cache.
15:24:19 # TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
15:24:19 # VALUE is the current value for the KEY.
15:24:19 
15:24:19 ########################
15:24:19 # EXTERNAL cache entries
15:24:19 ########################
15:24:19 
15:24:19 //No help, variable specified on the command line.
15:24:19 CATKIN_BUILD_BINARY_PACKAGE:UNINITIALIZED=1
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_AR:FILEPATH=/usr/bin/ar
15:24:19 
15:24:19 //Choose the type of build, options are: None(CMAKE_CXX_FLAGS or
15:24:19 // CMAKE_C_FLAGS used) Debug Release RelWithDebInfo MinSizeRel.
15:24:19 CMAKE_BUILD_TYPE:STRING=None
15:24:19 
15:24:19 //Enable/Disable color output during build.
15:24:19 CMAKE_COLOR_MAKEFILE:BOOL=ON
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_CXX_COMPILER:FILEPATH=/usr/lib/ccache/x86_64-linux-gnu-g++
15:24:19 
15:24:19 //Flags used by the compiler during all build types.
15:24:19 CMAKE_CXX_FLAGS:STRING='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 '
15:24:19 
15:24:19 //Flags used by the compiler during debug builds.
15:24:19 CMAKE_CXX_FLAGS_DEBUG:STRING=-g
15:24:19 
15:24:19 //Flags used by the compiler during release builds for minimum
15:24:19 // size.
15:24:19 CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
15:24:19 
15:24:19 //Flags used by the compiler during release builds.
15:24:19 CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
15:24:19 
15:24:19 //Flags used by the compiler during release builds with debug info.
15:24:19 CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_C_COMPILER:FILEPATH=/usr/lib/ccache/x86_64-linux-gnu-gcc
15:24:19 
15:24:19 //Flags used by the compiler during all build types.
15:24:19 CMAKE_C_FLAGS:STRING='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 '
15:24:19 
15:24:19 //Flags used by the compiler during debug builds.
15:24:19 CMAKE_C_FLAGS_DEBUG:STRING=-g
15:24:19 
15:24:19 //Flags used by the compiler during release builds for minimum
15:24:19 // size.
15:24:19 CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
15:24:19 
15:24:19 //Flags used by the compiler during release builds.
15:24:19 CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
15:24:19 
15:24:19 //Flags used by the compiler during release builds with debug info.
15:24:19 CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
15:24:19 
15:24:19 //Flags used by the linker.
15:24:19 CMAKE_EXE_LINKER_FLAGS:STRING=
15:24:19 
15:24:19 //Flags used by the linker during debug builds.
15:24:19 CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release minsize builds.
15:24:19 CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release builds.
15:24:19 CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
15:24:19 
15:24:19 //Flags used by the linker during Release with Debug Info builds.
15:24:19 CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
15:24:19 
15:24:19 //Enable/Disable output of compile commands during generation.
15:24:19 CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_Fortran_COMPILER:FILEPATH=CMAKE_Fortran_COMPILER-NOTFOUND
15:24:19 
15:24:19 //No help, variable specified on the command line.
15:24:19 CMAKE_INSTALL_LOCALSTATEDIR:UNINITIALIZED=/var
15:24:19 
15:24:19 //Install path prefix, prepended onto install directories.
15:24:19 CMAKE_INSTALL_PREFIX:PATH=/opt/ros/kinetic
15:24:19 
15:24:19 //No help, variable specified on the command line.
15:24:19 CMAKE_INSTALL_SYSCONFDIR:UNINITIALIZED=/etc
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_LINKER:FILEPATH=/usr/bin/ld
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
15:24:19 
15:24:19 //Flags used by the linker during the creation of modules.
15:24:19 CMAKE_MODULE_LINKER_FLAGS:STRING=
15:24:19 
15:24:19 //Flags used by the linker during debug builds.
15:24:19 CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release minsize builds.
15:24:19 CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release builds.
15:24:19 CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
15:24:19 
15:24:19 //Flags used by the linker during Release with Debug Info builds.
15:24:19 CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_NM:FILEPATH=/usr/bin/nm
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
15:24:19 
15:24:19 //No help, variable specified on the command line.
15:24:19 CMAKE_PREFIX_PATH:UNINITIALIZED=/opt/ros/kinetic
15:24:19 
15:24:19 //Value Computed by CMake
15:24:19 CMAKE_PROJECT_NAME:STATIC=automotive_platform_msgs
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
15:24:19 
15:24:19 //Flags used by the linker during the creation of dll's.
15:24:19 CMAKE_SHARED_LINKER_FLAGS:STRING=
15:24:19 
15:24:19 //Flags used by the linker during debug builds.
15:24:19 CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release minsize builds.
15:24:19 CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release builds.
15:24:19 CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
15:24:19 
15:24:19 //Flags used by the linker during Release with Debug Info builds.
15:24:19 CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
15:24:19 
15:24:19 //If set, runtime paths are not added when installing shared libraries,
15:24:19 // but are added when building.
15:24:19 CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
15:24:19 
15:24:19 //If set, runtime paths are not added when using shared libraries.
15:24:19 CMAKE_SKIP_RPATH:BOOL=NO
15:24:19 
15:24:19 //Flags used by the linker during the creation of static libraries.
15:24:19 CMAKE_STATIC_LINKER_FLAGS:STRING=
15:24:19 
15:24:19 //Flags used by the linker during debug builds.
15:24:19 CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release minsize builds.
15:24:19 CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
15:24:19 
15:24:19 //Flags used by the linker during release builds.
15:24:19 CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
15:24:19 
15:24:19 //Flags used by the linker during Release with Debug Info builds.
15:24:19 CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
15:24:19 
15:24:19 //Path to a program.
15:24:19 CMAKE_STRIP:FILEPATH=/usr/bin/strip
15:24:19 
15:24:19 //If this value is on, makefiles will be generated without the
15:24:19 // .SILENT directive, and all commands will be echoed to the console
15:24:19 // during the make.  This is useful for debugging only. With Visual
15:24:19 // Studio IDE projects all commands are done without /nologo.
15:24:19 CMAKE_VERBOSE_MAKEFILE:BOOL=ON
15:24:19 
15:24:19 //Value Computed by CMake
15:24:19 automotive_platform_msgs_BINARY_DIR:STATIC=/tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1/obj-x86_64-linux-gnu
15:24:19 
15:24:19 //Value Computed by CMake
15:24:19 automotive_platform_msgs_SOURCE_DIR:STATIC=/tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1
15:24:19 
15:24:19 
15:24:19 ########################
15:24:19 # INTERNAL cache entries
15:24:19 ########################
15:24:19 
15:24:19 //ADVANCED property for variable: CMAKE_AR
15:24:19 CMAKE_AR-ADVANCED:INTERNAL=1
15:24:19 //This is the directory where this CMakeCache.txt was created
15:24:19 CMAKE_CACHEFILE_DIR:INTERNAL=/tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1/obj-x86_64-linux-gnu
15:24:19 //Major version of cmake used to create the current loaded cache
15:24:19 CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3
15:24:19 //Minor version of cmake used to create the current loaded cache
15:24:19 CMAKE_CACHE_MINOR_VERSION:INTERNAL=5
15:24:19 //Patch version of cmake used to create the current loaded cache
15:24:19 CMAKE_CACHE_PATCH_VERSION:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_COLOR_MAKEFILE
15:24:19 CMAKE_COLOR_MAKEFILE-ADVANCED:INTERNAL=1
15:24:19 //Path to CMake executable.
15:24:19 CMAKE_COMMAND:INTERNAL=/usr/bin/cmake
15:24:19 //Path to cpack program executable.
15:24:19 CMAKE_CPACK_COMMAND:INTERNAL=/usr/bin/cpack
15:24:19 //Path to ctest program executable.
15:24:19 CMAKE_CTEST_COMMAND:INTERNAL=/usr/bin/ctest
15:24:19 //ADVANCED property for variable: CMAKE_CXX_COMPILER
15:24:19 CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_CXX_FLAGS
15:24:19 CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_CXX_FLAGS_DEBUG
15:24:19 CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_CXX_FLAGS_MINSIZEREL
15:24:19 CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_CXX_FLAGS_RELEASE
15:24:19 CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_CXX_FLAGS_RELWITHDEBINFO
15:24:19 CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_C_COMPILER
15:24:19 CMAKE_C_COMPILER-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_C_FLAGS
15:24:19 CMAKE_C_FLAGS-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_C_FLAGS_DEBUG
15:24:19 CMAKE_C_FLAGS_DEBUG-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_C_FLAGS_MINSIZEREL
15:24:19 CMAKE_C_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_C_FLAGS_RELEASE
15:24:19 CMAKE_C_FLAGS_RELEASE-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_C_FLAGS_RELWITHDEBINFO
15:24:19 CMAKE_C_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
15:24:19 //Executable file format
15:24:19 CMAKE_EXECUTABLE_FORMAT:INTERNAL=ELF
15:24:19 //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS
15:24:19 CMAKE_EXE_LINKER_FLAGS-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_DEBUG
15:24:19 CMAKE_EXE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
15:24:19 CMAKE_EXE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELEASE
15:24:19 CMAKE_EXE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
15:24:19 CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_EXPORT_COMPILE_COMMANDS
15:24:19 CMAKE_EXPORT_COMPILE_COMMANDS-ADVANCED:INTERNAL=1
15:24:19 //Name of external makefile project generator.
15:24:19 CMAKE_EXTRA_GENERATOR:INTERNAL=
15:24:19 //Name of generator.
15:24:19 CMAKE_GENERATOR:INTERNAL=Unix Makefiles
15:24:19 //Name of generator platform.
15:24:19 CMAKE_GENERATOR_PLATFORM:INTERNAL=
15:24:19 //Name of generator toolset.
15:24:19 CMAKE_GENERATOR_TOOLSET:INTERNAL=
15:24:19 //Source directory with the top level CMakeLists.txt file for this
15:24:19 // project
15:24:19 CMAKE_HOME_DIRECTORY:INTERNAL=/tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1
15:24:19 //Install .so files without execute permission.
15:24:19 CMAKE_INSTALL_SO_NO_EXE:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_LINKER
15:24:19 CMAKE_LINKER-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_MAKE_PROGRAM
15:24:19 CMAKE_MAKE_PROGRAM-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS
15:24:19 CMAKE_MODULE_LINKER_FLAGS-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_DEBUG
15:24:19 CMAKE_MODULE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL
15:24:19 CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELEASE
15:24:19 CMAKE_MODULE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO
15:24:19 CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_NM
15:24:19 CMAKE_NM-ADVANCED:INTERNAL=1
15:24:19 //number of local generators
15:24:19 CMAKE_NUMBER_OF_MAKEFILES:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_OBJCOPY
15:24:19 CMAKE_OBJCOPY-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_OBJDUMP
15:24:19 CMAKE_OBJDUMP-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_RANLIB
15:24:19 CMAKE_RANLIB-ADVANCED:INTERNAL=1
15:24:19 //Path to CMake installation.
15:24:19 CMAKE_ROOT:INTERNAL=/usr/share/cmake-3.5
15:24:19 //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS
15:24:19 CMAKE_SHARED_LINKER_FLAGS-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_DEBUG
15:24:19 CMAKE_SHARED_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
15:24:19 CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELEASE
15:24:19 CMAKE_SHARED_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO
15:24:19 CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_SKIP_INSTALL_RPATH
15:24:19 CMAKE_SKIP_INSTALL_RPATH-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_SKIP_RPATH
15:24:19 CMAKE_SKIP_RPATH-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS
15:24:19 CMAKE_STATIC_LINKER_FLAGS-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_DEBUG
15:24:19 CMAKE_STATIC_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL
15:24:19 CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELEASE
15:24:19 CMAKE_STATIC_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO
15:24:19 CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
15:24:19 //ADVANCED property for variable: CMAKE_STRIP
15:24:19 CMAKE_STRIP-ADVANCED:INTERNAL=1
15:24:19 //uname command
15:24:19 CMAKE_UNAME:INTERNAL=/bin/uname
15:24:19 //ADVANCED property for variable: CMAKE_VERBOSE_MAKEFILE
15:24:19 CMAKE_VERBOSE_MAKEFILE-ADVANCED:INTERNAL=1
15:24:19 
15:24:19 	cd /tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1
15:24:19 dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic -DCMAKE_PREFIX_PATH=/opt/ros/kinetic returned exit code 1
15:24:19 debian/rules:25: recipe for target 'override_dh_auto_configure' failed
15:24:19 make[1]: Leaving directory '/tmp/binarydeb/ros-kinetic-automotive-platform-msgs-3.0.1'
15:24:19 debian/rules:22: recipe for target 'build' failed
15:24:19 make[1]: *** [override_dh_auto_configure] Error 255
15:24:19 make: *** [build] Error 2
15:24:19 dpkg-buildpackage: error: debian/rules build gave error exit status 2
15:24:19 E: Building failed
15:24:19 Traceback (most recent call last):
15:24:19   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 138, in build_binarydeb
15:24:19     subprocess.check_call(cmd, cwd=source_dir)
15:24:19   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
15:24:19     raise CalledProcessError(retcode, cmd)
15:24:19 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-kinetic-automotive-platform-msgs']' returned non-zero exit status 1
15:24:19 
15:24:19 --------------------------------------------------------------------------------------------------
15:24:19 `apt-src build ros-kinetic-automotive-platform-msgs` failed.
15:24:19 This is usually because of an error building the package.
15:24:19 The traceback from this failure (just above) is printed for completeness, but you can ignore it.
15:24:19 You should look above `E: Building failed` in the build log for the actual cause of the failure.
15:24:19 --------------------------------------------------------------------------------------------------
15:24:19 
15:24:19 # END SUBSECTION
15:24:19 Build step 'Execute shell' marked build as failure
15:24:19 $ ssh-agent -k
</details>

Without an explicit dependency on the `ros_environment` package will not be available in the build environment. 

To do the comparision like https://github.com/astuff/automotive_autonomy_msgs/blob/2297c880652cf02cc47ab56f49c3dd222d3167cf/automotive_platform_msgs/CMakeLists.txt#L36

If it might evaluate to nothing a common workaround is to do a string comparison with a trailing whitespace on both sides. That will fix the error, but if you need this behavior the dependency should be added.

**Comment by tfoote** [comment]
Issue in dashing and 3.0.2 too https://github.com/ros/rosdistro/pull/23300

**Comment by JWhitleyWork** [comment]
@tfoote - I believe I have fixed the issue. Would you mind merging https://github.com/ros/rosdistro/pull/23436 to check?

**Comment by JWhitleyWork** [comment]
Thanks, Tully! Looks like the builds are back to normal.
