### ISSUE TITLE
ROS Foxy Release

### ISSUE THREAD

**Issue by JWhitleyWork** [astuff/platform_automation_msgs#17]
@icolwell-as Can I have someone at AS release this repo for ROS Foxy? It's somewhat urgent.

**Comment by icolwell-as** [comment]
We will look into this by the end of the week.

**Comment by JWhitleyWork** [comment]
Much appreciated!

**Comment by icolwell-as** [comment]
https://github.com/ros/rosdistro/pull/26598

**Comment by JWhitleyWork** [comment]
Thank you!
