### ISSUE TITLE
Message Description in VelocityAccelCov is Incorrect (?)

### ISSUE THREAD

**Issue by JWhitleyWork** [astuff/platform_automation_msgs#18]
The current message description in  `automotive_platform_msgs/msg/VelocityAccelCov` states:

```
# Vehicle Lateral Velocity and Acceleration Message with Covariance
```

I believe this message is actually meant to contain _longitudinal_ velocity, right?

**Comment by icolwell-as** [comment]
Yep, seems wrong to me, I'll open a fix. Thanks for reporting!
