### ISSUE TITLE
Package for ROS Noetic

### ISSUE THREAD

**Issue by fabianoboril** [astuff/platform_automation_msgs#20]
Hi everyone,

do you plan to provide a release for ROS Noetic (such that it is installable via apt)?

Thank you.

**Comment by icolwell-as** [comment]
We certainly can! Should be able to release within the next week or two.

**Comment by fabianoboril** [comment]
Awesome. Thank you very much :)

**Comment by icolwell-as** [comment]
Released to Noetic here: https://github.com/ros/rosdistro/pull/27156
Should be available via apt shortly after that merges.
