### ISSUE TITLE
Galactic Release

### ISSUE THREAD

**Issue by JWhitleyWork** [astuff/platform_automation_msgs#28]
Can we please get a release of the packages in this repo for ROS Galactic?

**Comment by icolwell-as** [comment]
@JWhitleyWork, sure! ETA is before end of August. Let me know if it's critical to get it earlier.

**Comment by icolwell-as** [comment]
https://github.com/ros/rosdistro/pull/30568

**Comment by JWhitleyWork** [comment]
Thanks!
