### ISSUE TITLE
Register for doc indexing with ROS buildfarm

### ISSUE THREAD

**Issue by gavanderhoorn** [astuff/platform_automation_msgs#9]
Sort-of related to #7: could you please submit this repository for documentation indexing to `ros/rosdistro`?

Without that indexing, the wiki pages for these packages are not that useful (ie: no auto-generated msg/srv docs, no api, etc).

I see a `release` and a `source` entry for `automotive_autonomy_msgs` ([here](https://github.com/ros/rosdistro/blob/18a3a38cd233bd88066826a664a6d3421c605f8d/melodic/distribution.yaml#L170-L184)), but no `doc` entry.

In case you need it, there is some guidance on how to do this here: [Indexing Your ROS Repository for Documentation Generation](http://wiki.ros.org/rosdistro/Tutorials/Indexing%20Your%20ROS%20Repository%20for%20Documentation%20Generation). But it really just comes down to adding an entry [like this](https://github.com/ros/rosdistro/blob/18a3a38cd233bd88066826a664a6d3421c605f8d/melodic/distribution.yaml#L150-L153) to the `distribution.yaml` of the targeted ROS release.

**Comment by JWhitleyWork** [comment]
Thanks for the hint. Done. PR: https://github.com/ros/rosdistro/pull/18868
